### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by ghost** [Tromiute/pidL#1]
you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao you suck at c++ lmao

**Comment by darik9pl** [comment]
im gonna upload a video that you suck at C++

**Comment by Tromiute** [comment]
Yeah These Is Not skid I'm made c++
